# Generated by Django 3.1.7 on 2021-03-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('e_mail', models.EmailField(max_length=254, unique=True)),
                ('bio', models.CharField(max_length=50, verbose_name='biography')),
                ('full_name', models.CharField(max_length=50)),
                ('profile_photo', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
