# Generated by Django 3.1.7 on 2021-03-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50, verbose_name='biography')),
                ('full_name', models.CharField(max_length=50)),
                ('profile_photo', models.CharField(max_length=50)),
            ],
        ),
    ]
