# Generated by Django 3.1.7 on 2021-03-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorp_app', '0004_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='being_followed',
        ),
        migrations.AddField(
            model_name='follow',
            name='followee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_followee', to='scorp_app.user'),
            preserve_default=False,
        ),
    ]
