# Generated by Django 3.1.7 on 2021-03-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorp_app', '0005_auto_20210330_1843'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'followee'), name='follow relation constraint'),
        ),
    ]
