# Generated by Django 3.1.7 on 2021-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorp_app', '0008_auto_20210403_1156'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='post',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['owner', 'created'], name='scorp_app_p_owner_i_f22a4c_idx'),
        ),
    ]
